# Generated by Django 6.0.6 on 2026-07-10 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, help_text='User first name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, help_text='User profile image', null=True, upload_to='images/accounts/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, help_text='User last name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number in international format', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain 9-15 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.CharField(help_text='Unique Telegram user ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Account last update timestamp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['telegram_id'], name='api_account_telegra_b9c639_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='api_account_created_941af1_idx'),
        ),
    ]
